US_STATES = [
    {'name': 'Alabama', 'population': 5074296, 'area': 135767, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Alabama.svg'},
    {'name': 'Alaska', 'population': 733406, 'area': 1723337, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Alaska.svg'},
    {'name': 'Arizona', 'population': 7359191, 'area': 295234, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arizona.svg'},
    {'name': 'Arkansas', 'population': 3013756, 'area': 137732, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arkansas.svg'},
    {'name': 'California', 'population': 38894236, 'area': 423967, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_California.svg'},
    {'name': 'Colorado', 'population': 5911606, 'area': 269601, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/4/46/Flag_of_Colorado.svg'},
    {'name': 'Connecticut', 'population': 3608477, 'area': 14357, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/9/96/Flag_of_Connecticut.svg'},
    {'name': 'Delaware', 'population': 1031967, 'area': 6446, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Flag_of_Delaware.svg'},
    {'name': 'Florida', 'population': 22377446, 'area': 170312, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Florida.svg'},
    {'name': 'Georgia', 'population': 10912876, 'area': 153910, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_the_State_of_Georgia.svg'},
    {'name': 'Hawaii', 'population': 1441553, 'area': 28313, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Hawaii.svg'},
    {'name': 'Idaho', 'population': 1948692, 'area': 216443, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_Idaho.svg'},
    {'name': 'Illinois', 'population': 12582032, 'area': 149995, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Illinois.svg'},
    {'name': 'Indiana', 'population': 6842385, 'area': 94326, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Flag_of_Indiana.svg'},
    {'name': 'Iowa', 'population': 3193079, 'area': 145746, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Iowa.svg'},
    {'name': 'Kansas', 'population': 2937150, 'area': 213100, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Kansas.svg'},
    {'name': 'Kentucky', 'population': 4546607, 'area': 104656, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Flag_of_Kentucky.svg'},
    {'name': 'Louisiana', 'population': 4624047, 'area': 135659, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Flag_of_Louisiana.svg'},
    {'name': 'Maine', 'population': 1385340, 'area': 91633, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/3/35/Flag_of_Maine.svg'},
    {'name': 'Maryland', 'population': 6165129, 'area': 32131, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Maryland.svg'},
    {'name': 'Massachusetts', 'population': 6893574, 'area': 27336, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Flag_of_Massachusetts.svg'},
    {'name': 'Michigan', 'population': 10045029, 'area': 250487, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Flag_of_Michigan.svg'},
    {'name': 'Minnesota', 'population': 5737051, 'area': 225163, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Minnesota.svg'},
    {'name': 'Mississippi', 'population': 2940055, 'area': 125438, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/4/42/Flag_of_Mississippi.svg'},
    {'name': 'Missouri', 'population': 6168187, 'area': 180540, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Flag_of_Missouri.svg'},
    {'name': 'Montana', 'population': 1104271, 'area': 380831, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_Montana.svg'},
    {'name': 'Nebraska', 'population': 1963692, 'area': 200330, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Flag_of_Nebraska.svg'},
    {'name': 'Nevada', 'population': 3177772, 'area': 286380, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Flag_of_Nevada.svg'},
    {'name': 'New Hampshire', 'population': 1388992, 'area': 24214, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_New_Hampshire.svg'},
    {'name': 'New Jersey', 'population': 9267130, 'area': 22591, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_New_Jersey.svg'},
    {'name': 'New Mexico', 'population': 2113344, 'area': 314917, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_New_Mexico.svg'},
    {'name': 'New York', 'population': 19453561, 'area': 141297, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_New_York.svg'},
    {'name': 'North Carolina', 'population': 10698973, 'area': 139391, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Flag_of_North_Carolina.svg'},
    {'name': 'North Dakota', 'population': 780588, 'area': 183108, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Flag_of_North_Dakota.svg'},
    {'name': 'Ohio', 'population': 11780017, 'area': 116098, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Ohio.svg'},
    {'name': 'Oklahoma', 'population': 4019800, 'area': 181037, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Oklahoma.svg'},
    {'name': 'Oregon', 'population': 4233635, 'area': 254799, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Oregon.svg'},
    {'name': 'Pennsylvania', 'population': 12820889, 'area': 119280, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Pennsylvania.svg'},
    {'name': 'Rhode Island', 'population': 1097379, 'area': 4001, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Rhode_Island.svg'},
    {'name': 'South Carolina', 'population': 5282634, 'area': 82933, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/6/69/Flag_of_South_Carolina.svg'},
    {'name': 'South Dakota', 'population': 909824, 'area': 199729, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_South_Dakota.svg'},
    {'name': 'Tennessee', 'population': 7092652, 'area': 109153, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Tennessee.svg'},
    {'name': 'Texas', 'population': 30428457, 'area': 695662, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Texas.svg'},
    {'name': 'Utah', 'population': 3402494, 'area': 219882, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Utah.svg'},
    {'name': 'Vermont', 'population': 647464, 'area': 24906, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Vermont.svg'},
    {'name': 'Virginia', 'population': 8779522, 'area': 110787, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Virginia.svg'},
    {'name': 'Washington', 'population': 7887012, 'area': 184661, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/5/54/Flag_of_Washington.svg'},
    {'name': 'West Virginia', 'population': 1767858, 'area': 62756, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/2/22/Flag_of_West_Virginia.svg'},
    {'name': 'Wisconsin', 'population': 5837462, 'area': 169635, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/2/22/Flag_of_Wisconsin.svg'},
    {'name': 'Wyoming', 'population': 586485, 'area': 253335, 'flag': 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Wyoming.svg'},
]

